version: "3.8"

services:
  mongo:
    image: mongo:6.0.9
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  db_data:
